### ISSUE TITLE
Error: Element from loaders list should have one of the fields 'loader' or 'loaders'

### ISSUE THREAD

**Issue by betimer** [webpack/core#32]
Got the error message below, when doing babel-node tools/distServer.js (open-src)

Error: Element from loaders list should have one of the fields 'loader' or 'loaders'
    at getLoadersFromObject (C:\Repo\vcm-spa\app\node_modules\webpack-core\lib\LoadersList.js:60:8)
    at LoadersList.<anonymous> (C:\Repo\vcm-spa\app\node_modules\webpack-core\lib\LoadersList.js:78:12)
    at Array.map (native)
    at LoadersList.match (C:\Repo\vcm-spa\app\node_modules\webpack-core\lib\LoadersList.js:70:19)
    at C:\Repo\vcm-spa\app\node_modules\webpack\lib\NormalModuleFactory.js:111:68
    at C:\Repo\vcm-spa\app\node_modules\async\lib\async.js:726:13
    at C:\Repo\vcm-spa\app\node_modules\async\lib\async.js:52:16
    at done (C:\Repo\vcm-spa\app\node_modules\async\lib\async.js:246:17)
    at C:\Repo\vcm-spa\app\node_modules\async\lib\async.js:44:16
    at C:\Repo\vcm-spa\app\node_modules\async\lib\async.js:723:17
ERROR: "open-src" exited with 1.

Source file of srcServer.js
```
// This file configures the development web server
// which supports hot reloading and synchronized testing.

// Require Browsersync along with webpack and middleware for it
import browserSync from 'browser-sync';
// Required for react-router browserHistory
// see https://github.com/BrowserSync/browser-sync/issues/204#issuecomment-102623643
import historyApiFallback from 'connect-history-api-fallback';
import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';
import config from '../webpack.config.dev';

const bundler = webpack(config);

// Run Browsersync and use middleware for Hot Module Replacement
browserSync({
  server: {
    baseDir: 'src',
    middleware: [
      webpackDevMiddleware(bundler, {
        // Dev middleware can't access config, so we provide publicPath
        publicPath: config.output.publicPath,

        // pretty colored output
        stats: { colors: true },

        // Set to false to display a list of each file that is being bundled.
        noInfo: true,
        quiet:true
        // for other settings see
        // http://webpack.github.io/docs/webpack-dev-middleware.html
      }),
      // bundler should be the same as above
      webpackHotMiddleware(bundler),
      historyApiFallback()
    ]
  },

  // no need to watch '*.js' here, webpack will take care of it for us,
  // including full page reloads if HMR won't work
  files: [
    'src/*.html'
  ]
});

```

**Comment by VaishaliRavindran** [comment]
I am facing the same issue. How to solve it ?
